# scripts/process_courses.py
import os
import sys

def main():
    out_dir = "outputs/a4"
    os.makedirs(out_dir, exist_ok=True)

    tex_path = os.path.join(out_dir, "master_syllabus.tex")

    tex_content = r"""
\documentclass[a4paper,11pt]{article}
\usepackage{geometry}
\geometry{margin=20mm}
\begin{document}
\section*{Test A4 Syllabus Book}
This PDF was generated by GitHub Actions.
\end{document}
"""

    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(tex_content)

    print(f"Generated {tex_path}")

if __name__ == "__main__":
    main()
